[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "python -u main.py"
healthcheckPath = "/health"
healthcheckTimeout = 100

[variables]
PYTHONMALLOC = "malloc"
MALLOC_TRIM_THRESHOLD_ = "100000"
PYTHONUNBUFFERED = "1"
